### ISSUE TITLE
Misleading stack trace on unexpected status code

### ISSUE THREAD

**Issue by sakovias** [WhoopInc/supertest-as-promised#24] opened 2016-02-20 13:51 UTC
That's a very useful library. I like using promises in both application and test code.

Here's my simple failing test that uses `supertest-as-promised`:
``` javascript
'use strict';
var request = require('supertest-as-promised');
request('www.example.com')
  .post('/')
  .expect(200)
  .then(function(res) {
    console.log('Success\n', res.body);
  })
  .catch(function(err) {
    console.log(err.stack);
  });
```
The output of this shows a stack trace leading to the library code, but not to the `.expect()` line in my code that was failing:
```
$ node supertest-as-promised-test.js 
Error: expected 200 "OK", got 411 "Length Required"
    at Test._assertStatus (/path/to/node_modules/supertest/lib/test.js:232:12)
    at Test._assertFunction (/path/to/node_modules/supertest/lib/test.js:247:11)
    at Test.assert (/path/to/node_modules/supertest/lib/test.js:148:18)
    at assert (/path/to/node_modules/supertest/lib/test.js:127:12)
    at /path/to/node_modules/supertest/lib/test.js:124:5
    at Test.Request.callback (/path/to/node_modules/supertest/node_modules/superagent/lib/node/index.js:831:3)
    at IncomingMessage.<anonymous> (/path/to/node_modules/supertest/node_modules/superagent/lib/node/index.js:1049:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:448:13)
```
I've checked with the original `supertest` that proper stack trace is returned there.

**Comment by benesch** [comment] 2016-02-20 15:33
Promises notoriously have bad support for stack traces, but Bluebird, the underlying Promise library, supports enabling long stack traces in development. Turn on long stack traces like so:

```
BLUEBIRD_LONG_STACK_TRACES=1 BLUEBIRD_WARNINGS=1 node test.js
```

More information: http://bluebirdjs.com/docs/api/promise.config.html

**Comment by benesch** [comment] 2016-02-20 19:12
Marking this as working as intended.

**Closed by benesch** 2016-02-20 19:12 UTC

**Comment by sakovias** [comment] 2016-02-21 02:57
Thanks @benesch.

I wasn't quite clear in my original description and I think I've missed that the problem is actually in `supertest` itself. This code does give an indication of where the error occurs, but only because I was throwing the error myself:
``` javascript
'use strict';
var request = require('supertest');
request('www.example.com')
  .post('/')
  .expect(200)
  .end(function(err, res) {
    if (err) throw err;
    console.log('Success:\n', res.body);
  });
```
This gives an error indication
```
/path/supertest-test.js:7
    if (err) throw err;
                   ^
Error: expected 200 "OK", got 411 "Length Required"
    at Test._assertStatus (/path/node_modules/supertest/lib/test.js:232:12)
    at Test._assertFunction (/path/node_modules/supertest/lib/test.js:247:11)
    ...
```
but the stack trace origin points to `supertest`, not my test. So `.expect` is not like a test framework assertion, it just tells that something went wrong. 

In my Mocha `before()` hooks I send a bunch of requests in parallel (each prepared with `supertest-as-promised`) and if one of them fails I get an error like
```
expected 200 "OK", got 500 "Internal Server Error"
```
which doesn't tell me which of the requests failed. If I understand that correctly, this would happen regardless of whether I use `supertest` or `supertest-as-promissed`.

I guess I just need to move the status code check part into the `.then()` handler, e.g. `res.statusCode.should.equal(200)`.

**Comment by benesch** [comment] 2016-02-21 22:51
Sorry, I gave you instructions for the current version of Bluebird (v3), when SuperTest as Promised ships with Bluebird v2 by default. Upgrade to SuperTest as Promised v3—just published—and enabling long stack traces will work as I've described above. Here's the output on my machine.

```
$ BLUEBIRD_LONG_STACK_TRACES=1 BLUEBIRD_WARNINGS=1 node t.js
TypeError: Cannot read property 'status' of undefined
    at Test._assertStatus (/Users/benesch/Desktop/node_modules/supertest/lib/test.js:229:10)
    at Test._assertFunction (/Users/benesch/Desktop/node_modules/supertest/lib/test.js:247:11)
    at Test.assert (/Users/benesch/Desktop/node_modules/supertest/lib/test.js:148:18)
    at assert (/Users/benesch/Desktop/node_modules/supertest/lib/test.js:127:12)
    at /Users/benesch/Desktop/node_modules/supertest/lib/test.js:124:5
    at Test.Request.callback (/Users/benesch/Desktop/node_modules/superagent/lib/node/index.js:815:12)
    at ClientRequest.<anonymous> (/Users/benesch/Desktop/node_modules/superagent/lib/node/index.js:767:10)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketErrorListener (_http_client.js:265:9)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at connectErrorNT (net.js:996:8)
    at doNTCallback2 (node.js:450:9)
    at process._tickCallback (node.js:364:17)
From previous event:
    at Test.toPromise (/Users/benesch/Desktop/node_modules/supertest-as-promised/index.js:15:12)
    at Test.then (/Users/benesch/Desktop/node_modules/supertest-as-promised/index.js:27:17)
    at Object.<anonymous> (/Users/benesch/Desktop/t.js:6:4)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)
    at node.js:972:3

```

**Comment by sakovias** [comment] 2016-02-28 12:16
Thanks @benesh. Will keep Bluebird v3 settings in mind.

Just for the reference, I've opened an issue at Supertest's repository that was at the root of my problem with `expect()` checks https://github.com/visionmedia/supertest/issues/317.
