### ISSUE TITLE
With supertest 1.0.0, expect()s for non-2XX response codes return a rejected Promise

### ISSUE THREAD

**Issue by sobotklp** [WhoopInc/supertest-as-promised#10] opened 2015-05-12 23:09 UTC
For example, if a URL returns a 404 error code, and we have the following test case to ensure the 404 response:
```
it("should fulfill with a non-200 response ", function () {
  return expect(request.get("/notfound").expect(404)).to.eventually.be.fulfilled;
});
```

will fail. It will return a rejected promise instead. However, the behaviour when using supertest 0.15.0 is to return a fulfilled promise, and the test case above would pass.

**Comment by benesch** [comment] 2015-05-13 00:26
Oh no! That's pretty awful—but I can't reproduce.

See the test case I just pushed to master: c98740e. I cherry-picked this against 1.0.0 too, and wasn't able to repro.

**Comment by benesch** [comment] 2015-05-13 00:28
Oh, my bad. *SuperTest* @ 1.0.0, not SuperTest as Promised. Let me re-investigate.

**Comment by benesch** [comment] 2015-05-13 00:33
Agh! This is an intentional upstream design decision discussed in visionmedia/superagent#283.

I think SuperTest as Promised's behavior here is correct; if upstream is throwing an error, the only faithful and correct behavior is to reject the promise. Oh well.

**Comment by sobotklp** [comment] 2015-05-13 01:42
Thanks for looking into that. I'll adapt my test cases to use superagent's new behaviour.

**Comment by sobotklp** [comment] 2015-05-13 02:28
Actually I probably won't. I think the behaviour is correct for a HTTP request library, but incorrect for a HTTP testing tool. A related issue is open on SuperTest: https://github.com/visionmedia/supertest/issues/221

**Comment by benesch** [comment] 2015-05-13 03:18
Yeah, upon further inspection, I agree. Shoutout to @dougwilson for filing visionmedia/supertest#224. 

If that doesn't get merged upstream, let's either apply it here or allow users to use supertest-as-promised with a forked version of supertest, à la [superagent-ls](https://github.com/kmalakoff/superagent-ls).

**Comment by benesch** [comment] 2015-05-13 17:09
And the patch has landed in supertest. Cheers!

**Closed by benesch** 2015-05-13 17:09 UTC

**Comment by camjackson** [comment] 2015-06-19 10:19
Are you sure this is working properly? With supertest-as-promised 2.0.1, and supertest 1.0.1, I'm still getting test failures on tests where I expect a 3xx status code :(

You can see this at the moment in camjackson/writeitdown, or I can try to build a simple repro if you want?

**Comment by dougwilson** [comment] 2015-06-19 13:45
@camjackson you have to expect the status code on `superagent` itself, rather than in your fulfilled function. Example correct way with your code:
```js
        return request(app)
          .post('/login')
          .type('form')
          .send({
            username: 'bad-user',
            password: 'bad-password'
          })
          .expect(302) // <-- you need to expect the status code here
          .expect('Location', '/login');
```

**Comment by benesch** [comment] 2015-06-19 22:36
Thanks, @dougwilson!

**Comment by camjackson** [comment] 2015-06-22 13:53
Hmm, that does work, but I'm still a bit unsure. The old behaviour was that the promise returned by this this:

    request(app).get('/login')

would eventually be fulfilled, in the case where the HTTP status is non-200.

The new behaviour is that such a promise is rejected, which is exactly in line with the changes to superagent, which suggests to me that the problems caused by the superagent change have not been resolved here.

Perhaps my example is not the best one, but what if I needed to do a more custom expectation? I'd be stuck with doing it in the rejected promise, rather than the fulfilled one, which was not the right way to operate, according to the discussion made in the linked supertest thread.

All of that aside, it's probably not the best idea for supertest-as-promised to just have the supertest version set as `*`, as it leaves users of this library open to breaking changes from sub-dependencies, which is what happened to me. My dependencies worked one day, and were broken the next!

**Comment by benesch** [comment] 2015-06-22 18:36
The best explanation is probably reading @dougwilson's bugfix commit visionmedia/supertest@4a11955. Since v1.0.0, SuperAgent raises an error on a non-2xx status code. SuperTest passes that error through *unless* you've instructed it to expect that specific "failing" status code and ignore the error for you.

So if you want to do something custom, expect the "failing" status code on SuperTest itself so that the SuperTest strips the SuperAgent error, and then you'll have a fulfilled promise like before:

```js
request(app)
    .get('/login')
    .expect(301)
    .then(function (res) { assertVeryComplicatedExpression(res) })
```

It's not ideal, but seemed to be the best compromise between SuperAgent's new behavior and the behavior you'd expect from a test HTTP client like SuperTest. Per the discussion above, I'd rather this library be a dumb wrapper that directly converts the callback API to a promise API without introducing any behavior changes. But I'd be open to allowing users to wrap arbitrary forks of SuperTest so you can swap in the behavior you want.

Regarding the version dependency, the README notes

> SuperTest as Promised lists supertest as a peer dependency, so it'll wrap whatever version of SuperTest you've asked for in your own package.json. If you don't specify a version of SuperTest, npm will use the latest.

so just drop your own version requirement for `supertest` into your `package.json` and you'll be good to go. And big win: in npm@3, [peer dependencies will not be automatically installed](https://github.com/npm/npm/issues/6565), so you'll *always* have to explicitly list the version requirement in your own package.json.

**Comment by camjackson** [comment] 2015-06-22 22:39
Great, that all makes perfect sense! Thanks for taking the time to explain it to me :)

**Comment by benesch** [comment] 2015-06-24 18:11
Of course! Thanks for using SuperTest as Promised! Let us know if you run into any other annoyances.
